language: node_js
node_js:
    - '5.10'
env:
    - NODE_ENV=production
before_script:
    - npm install
script:
    - npm test
    - npm run lint
after_success:
    - npm run test:coveralls
cache:
  directories:
    - node_modules